runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /CSS
  static_dir: stylesheet
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
